#pragma once


#define APEX_MATH_VECTOR4_SWIZZLE(c1,c2,c3,c4) constexpr Vector4 c1##c2##c3##c4() const { return { c1, c2, c3, c4 }; }
#define APEX_MATH_VECTOR3_SWIZZLE(c1,c2,c3) constexpr Vector3 c1##c2##c3() const { return { c1, c2, c3 }; }
#define APEX_MATH_VECTOR2_SWIZZLE(c1,c2) constexpr Vector2 c1##c2() const { return { c1, c2 }; }

#define APEX_MATH_VECTOR2_SWIZZLES(a,b) \
		APEX_MATH_VECTOR2_SWIZZLE(a,a) \
		APEX_MATH_VECTOR2_SWIZZLE(a,b) \
		APEX_MATH_VECTOR2_SWIZZLE(b,a) \
		APEX_MATH_VECTOR2_SWIZZLE(b,b)

#define APEX_MATH_VECTOR3_SWIZZLES(a,b,c) \
		APEX_MATH_VECTOR3_SWIZZLE(a,a,a) \
		APEX_MATH_VECTOR3_SWIZZLE(a,a,b) \
		APEX_MATH_VECTOR3_SWIZZLE(a,a,c) \
		APEX_MATH_VECTOR3_SWIZZLE(a,b,a) \
		APEX_MATH_VECTOR3_SWIZZLE(a,b,b) \
		APEX_MATH_VECTOR3_SWIZZLE(a,b,c) \
		APEX_MATH_VECTOR3_SWIZZLE(a,c,a) \
		APEX_MATH_VECTOR3_SWIZZLE(a,c,b) \
		APEX_MATH_VECTOR3_SWIZZLE(a,c,c) \
		APEX_MATH_VECTOR3_SWIZZLE(b,a,a) \
		APEX_MATH_VECTOR3_SWIZZLE(b,a,b) \
		APEX_MATH_VECTOR3_SWIZZLE(b,a,c) \
		APEX_MATH_VECTOR3_SWIZZLE(b,b,a) \
		APEX_MATH_VECTOR3_SWIZZLE(b,b,b) \
		APEX_MATH_VECTOR3_SWIZZLE(b,b,c) \
		APEX_MATH_VECTOR3_SWIZZLE(b,c,a) \
		APEX_MATH_VECTOR3_SWIZZLE(b,c,b) \
		APEX_MATH_VECTOR3_SWIZZLE(b,c,c) \
		APEX_MATH_VECTOR3_SWIZZLE(c,a,a) \
		APEX_MATH_VECTOR3_SWIZZLE(c,a,b) \
		APEX_MATH_VECTOR3_SWIZZLE(c,a,c) \
		APEX_MATH_VECTOR3_SWIZZLE(c,b,a) \
		APEX_MATH_VECTOR3_SWIZZLE(c,b,b) \
		APEX_MATH_VECTOR3_SWIZZLE(c,b,c) \
		APEX_MATH_VECTOR3_SWIZZLE(c,c,a) \
		APEX_MATH_VECTOR3_SWIZZLE(c,c,b) \
		APEX_MATH_VECTOR3_SWIZZLE(c,c,c)
